POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Understanding the Node.js Event Loop",
  "author": "Ryan Dahl",
  "url": "https://nodejs.org/en/blog/event-loop",
  "likes": 42
}
